server:
  port: 5006

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankAccount
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



spring.cloud.stream:
  function:
    definition: supplier;consumer
  bindings:
    supplier-out-0:
      destination: Account-created
    consumer-in-0:
      destination: Account-updated
